--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2 (Debian 12.2-1.pgdg100+1)
-- Dumped by pg_dump version 12.2 (Debian 12.2-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: shotservice; Type: DATABASE; Schema: -; Owner: shotservice
--

-- CREATE DATABASE shotservice WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';


-- ALTER DATABASE shotservice OWNER TO shotservice;

-- \connect shotservice

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: shot; Type: TABLE; Schema: public; Owner: shotservice
--

CREATE TABLE public.shot (
    id bigint NOT NULL,
    camera_movement character varying(127) DEFAULT NULL::character varying,
    in_point integer NOT NULL,
    out_point integer NOT NULL,
    shot_type character varying(127) DEFAULT NULL::character varying,
    video_id bigint NOT NULL,
    CONSTRAINT shot_in_point_check CHECK ((in_point >= 0)),
    CONSTRAINT shot_out_point_check CHECK ((out_point >= 0))
);


--
-- Name: shot_id_seq; Type: SEQUENCE; Schema: public; Owner: shotservice
--

ALTER TABLE public.shot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shot shot_pkey; Type: CONSTRAINT; Schema: public; Owner: shotservice
--

ALTER TABLE ONLY public.shot
    ADD CONSTRAINT shot_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

